### ISSUE TITLE
Compilation error: ContextBootstrapInitializer.java:[24,56] cannot find symbol

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-native#20]
I get this error when trying to follow the instructions in [my forthcoming JHipster Native blog post](https://deploy-preview-1088--okta-blog.netlify.app/blog/2022/02/28/spring-native-jhipster). I swear it worked last week!

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/mraible/Downloads/jhipster-native/target/generated-runtime-sources/spring-aot/
  src/main/java/org/springframework/cache/annotation/ContextBootstrapInitializer.java:[24,56] cannot find symbol
  symbol:   method setConfigurers(java.lang.Object)
  location: variable bean of type org.springframework.cache.jcache.config.ProxyJCacheConfiguration
[INFO] 1 error
```

I'm not sure how to fix this since it's a generated class.

If I revert to Spring Native 0.11.2, it happens too.

**Comment by mraible** [comment]
It seems like [this code](https://github.com/jhipster/generator-jhipster-native/blob/main/generators/server/generator.mjs#L18) isn't working for some reason.

**Comment by mraible** [comment]
I'm not sure if it's related, but I also get this error when I first create the app.

```
sh: rimraf: command not found
ERROR! Command failed with exit code 127: npm run clean-www
```

Steps to reproduce:

```
git clone https://github.com/oktadev/auth0-full-stack-java-example.git jhipster-native
cd jhipster-native
rm -rf *
jhipster-native --with-entities
```

**Comment by mshima** [comment]
> Steps to reproduce:
> 
> ```
> git clone https://github.com/oktadev/auth0-full-stack-java-example.git jhipster-native
> cd jhipster-native
> rm -rf *
> jhipster-native --with-entities
> ```

Tested using `-b spring-native` at clone command and the error didn't happened.
`jhipster-native` should be used with `--skip-jhipster-dependencies` since it's not released yet (already done at native branch).

**Comment by mraible** [comment]
If I do the following, my apps still has caching:

```
npm i -g "mshima/generator-jhipster-native#config"
git clone https://github.com/oktadev/auth0-full-stack-java-example.git jhipster-native
cd jhipster-native
rm -rf *
jhipster-native --with-entities --skip-jhipster-dependencies
```

If I cat the `.yo-rc.json` file for `cache`, it shows ehcache is still enabled.

```
$ cat .yo-rc.json | grep cache
    "cacheProvider": "ehcache",
```

**Comment by mraible** [comment]
Hmmmm, I thought it would update `.yo-rc.json` to disable caching. For my blog post, should I change it from:

```
rm -rf *
jhipster-native --with-entities
```

To:

```
rm -rf *
```

Edit `.yo-rc.json` to disable caching and disable Hibernate's cache (since it's not supported by Spring Native yet).

```json
"cacheProvider": "no",
"enableHibernateCache": false,
```

Then, re-create your app:

```
jhipster-native --with-entities
```
