### ISSUE TITLE
Add Gradle support

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-native#24]
/cc @atomfrede

**Comment by atomfrede** [comment]
Will have look.

**Comment by mraible** [comment]
Increasing the bounty on this one since it's more work than expected.

**Comment by atomfrede** [comment]
@mraible Should I claim the whole bounty, should we split it (2/3, 1/3) or do you want to give an extra bounty to @mshima for the whole ci part?

**Comment by mshima** [comment]
@atomfrede take the whole
