### ISSUE TITLE
GitHub Actions don't work by default

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-native#39]
I discovered a number of issues when updating my (still in draft) blog post about [GitHub Actions and GraalVM](https://github.com/oktadev/okta-blog/pull/1098).

1. The first build fails by default because of `--remove-orphans`. I reported [this issue](https://github.com/jhipster/generator-jhipster/issues/18387) and closed it, but it's still an issue for this particular tutorial. You can see how it fails, then works in https://github.com/mraible/jhipster-flickr2/pull/1. 
2. Triggering the `native.yml` workflow fails with the following error:

        The job running on runner GitHub Actions 2 has exceeded the maximum execution time of 40 minutes.

3. The release build for Windows fails because it tries to use `./mvnw` to build the app.

        Run npm run native-package -- -B -ntp "-Dnative-image-name=flickr2-Windows-v0.0.1-x86_64"
         
        > flickr-2@0.0.1-SNAPSHOT native-package
        > ./mvnw package -Pnative,prod -DskipTests "-B" "-ntp" "-Dnative-image-name=flickr2-Windows-v0.0.1-x86_64"

        '.' is not recognized as an internal or external command,

4. The release build for Linux fails at 1h 29m 44s. I'm guessing this is a timeout issue. I've had issues with Linux in the past and solved it by allocating more memory to the `native-maven-plugin` with `<buildArg>--no-fallback -J-Xmx10g</buildArg>`.

You can see these failed workflows at https://github.com/mraible/jhipster-flickr2/actions.

**Comment by mraible** [comment]
To solve the 2nd issue, I tried changing to `macos-latest` instead of `linux-latest` since I know that works without adjusting memory settings. It fails with the following error.

```
Run npm run ci:e2e:prepare

> flickr-2@0.0.1-SNAPSHOT ci:e2e:prepare
> npm run ci:e2e:prepare:docker


> flickr-2@0.0.1-SNAPSHOT ci:e2e:prepare:docker
> npm run docker:db:up && npm run docker:others:up && docker ps -a


> flickr-2@0.0.1-SNAPSHOT docker:db:up
> docker-compose -f src/main/docker/postgresql.yml up -d

sh: docker-compose: command not found
```

This appears to be because you [have to install docker-compose with homebrew on macos-latest](https://stackoverflow.com/a/64647004/65681).

**Comment by mraible** [comment]
For the 3rd issue, I tried changing from `./mvnw` to `mvn` and that gets the Windows further along. I now [runs out of memory](https://github.com/mraible/jhipster-flickr2/runs/6063246551?check_suite_focus=true) just after 26m.

**Comment by mshima** [comment]
> This appears to be because you [have to install docker-compose with homebrew on macos-latest](https://stackoverflow.com/a/64647004/65681).

Yes. GitHub doesn't have the license to include docker at MacOS by default.

https://github.com/jhipster/generator-jhipster-native/blob/3e79b5631b825fc86e8c3ffd27ad9a306e218834/.github/workflows/jdl.yml#L91-L98

> For the 3rd issue, I tried changing from `./mvnw` to `mvn` and that gets the Windows build further along. It now [runs out of memory](https://github.com/mraible/jhipster-flickr2/runs/6063246551?check_suite_focus=true) just after 26m.

At window we should use bash for `./mvnw` to work.
https://github.com/hipster-labs/jhipster-daily-builds/blob/5db8a76548a3c10df9c3a66c810316c7b68f20b0/.github/workflows/windows.yaml#L43-L45

For the timeout, we will need to enable the memory fine tune by default.
https://github.com/jhipster/generator-jhipster-native/blob/3e79b5631b825fc86e8c3ffd27ad9a306e218834/generators/ci-cd/templates/github-artifact.yml.ejs#L45-L60

I will create the appropriate PRs.

**Comment by mraible** [comment]
4th issue solved by [setting up pagefile for Linux](https://github.com/mraible/jhipster-flickr2/commit/ea432a31091a5e278790a210151f93091b80a22e). 

Windows build currently fails with:

```
Run (Get-CimInstance Win32_PageFileUsage).AllocatedBaseSize
  (Get-CimInstance Win32_PageFileUsage).AllocatedBaseSize
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
D:\a\_temp\c61a9967-cf50-47e2-b375-7a721de3ee31.sh: line 1: syntax error near unexpected token `.AllocatedBaseSize'
```

This might be caused by bash. I tried [adding msbuild](https://github.com/mraible/jhipster-flickr2/commit/0c0da599e01aca2082a76063f52a454000104c9e). If that doesn't work. I'll revert using bash and change `package.json` to use `mvn`.

**Comment by mraible** [comment]
Nope, adding msbuild [doesn't work](https://github.com/mraible/jhipster-flickr2/runs/6066150173?check_suite_focus=true). I'll try removing bash, msbuild, and changing `native-package` to use `mvn`.

**Comment by mraible** [comment]
It [_almost_ worked](https://github.com/mraible/jhipster-flickr2/runs/6066471179?check_suite_focus=true):

```
CreateFile target/flickr2-Windows-v0.0.1-x86_64: The system cannot find the file specified.
```

[This](https://github.com/mraible/jhipster-flickr2/commit/3c571a307c9a6aacff7c72a5a09fb0e7747dbc9c) should fix it.

**Comment by mraible** [comment]
It [worked](https://github.com/mraible/jhipster-flickr2/runs/6067205139?check_suite_focus=true)! Windows sure takes a while though.

Time to complete:

- Linux: 36m 43s
- Mac: 32m 29s
- Windows: 1h 3m 8s

**Comment by mraible** [comment]
The `native.yml` just [failed on a scheduled build](https://github.com/mraible/jhipster-flickr2/runs/6070390073?check_suite_focus=true). I googled the 137 error and it appears to be an out-of-memory error. I [configured a page file](https://github.com/mraible/jhipster-flickr2/commit/988285e0ccfbd643ea9aecc79891cd59c23f6fbf) to fix it.

**Comment by mshima** [comment]
It's missing to improve main GitHub workflows.

**Comment by mraible** [comment]
I believe this is fixed. I only left it open to track the bug bounty payment.

**Comment by mraible** [comment]
@mshima Please grab the bug bounty for this one.

**Comment by mshima** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/85382.

**Comment by DanielFran** [comment]
@mshima approved
