### ISSUE TITLE
[GitHub Actions]: Nightly build workflow fails

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-native#44]
I tried updating my [blog post PR]() to use the `main` branch. It fails to run the nightly build successfully. That's a bad developer experience and we should fix it. 

https://github.com/mraible/jhipster7-flickr2/actions/runs/2199460457

**Comment by mshima** [comment]
pom.xml is missing `native-build-args` property.
https://github.com/mraible/jhipster7-flickr2/blob/5af0633781f3a605401903e15bef7f615a334ab1/pom.xml#L106-L107.
