### ISSUE TITLE
Add jwt support 

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster-native#48]
While poking around with the gradle part I used mostly jwt instead of oauth. Eventually running the native image failed because of missing jjwt classes. Is that only related to gradle or do we only support oauth for now?

**Comment by mraible** [comment]
The [original examples](https://github.com/mraible/spring-native-examples) that Josh and I created only tested OAuth. We should support JWT. It's probably just a matter of adding type hints for classes instantiated with reflection.

**Comment by atomfrede** [comment]
Yes think so too, just wanted to make sure its not related to gradle.

**Comment by linghengqian** [comment]
Refer to https://github.com/jwtk/jjwt/issues/637#issuecomment-912839710 .

**Comment by atomfrede** [comment]
Thanks @linghengqian. Seems not to complicated (but I did say the same about adding gradle support 🤣)

**Comment by atomfrede** [comment]
@mshima Can you do a the release again?

**Comment by mshima** [comment]
@atomfrede done.
