### ISSUE TITLE
Upgrade to Spring Native 0.12.0

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-native#51]
[Release notes for 0.12.0](https://github.com/spring-projects-experimental/spring-native/releases/tag/0.12.0)

This likely requires Spring Boot 2.7.0, which is being worked on in https://github.com/jhipster/generator-jhipster/pull/18511.

**Comment by atomfrede** [comment]
Specially looking forward to the [devtools fix for gradle](https://github.com/spring-projects-experimental/spring-native/issues/1579) 🎉

**Comment by atomfrede** [comment]
@mraible @mshima Should be do a release with these changes (jh 7.9.2, latest spring native)?

**Comment by mraible** [comment]
Yes, I think we should! 

/cc @alina-yur

**Comment by alina-yur** [comment]
@atomfrede @mraible yes please!:)

**Comment by mshima** [comment]
I will do 2 more adjusts and release.

**Comment by mshima** [comment]
Version 1.3.0 is published.
